name: Publish to PyPI

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Use the latest version of actions/checkout

      - name: Set up Python
        uses: actions/setup-python@v4  # Use the latest version of setup-python
        with:
          python-version: 3.8  # You can modify this to a newer version if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine  # Essential build tools

      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel  # Generate source distribution and wheel file

      - name: Check for package validity
        run: |
          python -m twine check dist/*  # Ensure package validity before uploading

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}  # Store PyPI username securely
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}  # Store PyPI API token securely
        run: |
          twine upload dist/* --repository-url https://upload.pypi.org/legacy/
